#pragma once
#include <string>
#include <iostream>
#include <sstream>
#include <vector>
#include <algorithm>

namespace AsciiArt
{
    class Art
    {
    public:
        std::string getAsciiChar(char character);
        std::string getAsciiString(std::string toAscii);

    private:
        std::string exclamationMark =
            " !!!   \n"
            "!!:!!  \n"
            "!:::!  \n"
            "!:::!  \n"
            "!:::!  \n"
            "!:::!  \n"
            "!:::!  \n"
            "!:::!  \n"
            "!:::!  \n"
            "!:::!  \n"
            "!!:!!  \n"
            " !!!   \n"
            "       \n"
            " !!!   \n"
            "!!:!!  \n"
            " !!!   \n";
        std::string hashtag =
            "                            \n"
            "                            \n"
            "                            \n"
            "     ######    ######       \n"
            "     #::::#    #::::#       \n"
            "     #::::#    #::::#       \n"
            "######::::######::::######  \n"
            "#::::::::::::::::::::::::#  \n"
            "######::::######::::######  \n"
            "     #::::#    #::::#       \n"
            "     #::::#    #::::#       \n"
            "######::::######::::######  \n"
            "#::::::::::::::::::::::::#  \n"
            "######::::######::::######  \n"
            "     #::::#    #::::#       \n"
            "     #::::#    #::::#       \n"
            "     ######    ######       \n";
        std::string dollar =
            "       $$$$$        \n"
            "       $:::$        \n"
            "   $$$$$:::$$$$$$   \n"
            " $$::::::::::::::$  \n"
            "$:::::$$$$$$$::::$  \n"
            "$::::$       $$$$$  \n"
            "$::::$              \n"
            "$::::$              \n"
            "$:::::$$$$$$$$$     \n"
            " $$::::::::::::$$   \n"
            "   $$$$$$$$$:::::$  \n"
            "            $::::$  \n"
            "            $::::$  \n"
            "$$$$$       $::::$  \n"
            "$::::$$$$$$$:::::$  \n"
            "$::::::::::::::$$   \n"
            " $$$$$$:::$$$$$     \n"
            "      $:::$         \n"
            "      $$$$$         \n";
        std::string percent =
            " %%%%%         %%%%%%%  \n"
            "%:::::%       %:::::%   \n"
            "%:::::%      %:::::%    \n"
            " %%%%%      %:::::%     \n"
            "           %:::::%      \n"
            "          %:::::%       \n"
            "         %:::::%        \n"
            "        %:::::%         \n"
            "       %:::::%          \n"
            "      %:::::%           \n"
            "     %:::::%            \n"
            "    %:::::%             \n"
            "   %:::::%      %%%%%   \n"
            "  %:::::%      %:::::%  \n"
            " %:::::%       %:::::%  \n"
            "%%%%%%%         %%%%%   \n";
        std::string ampersand =
            "      &&&&&&&&&&      \n"
            "     &::::::::::&     \n"
            "    &::::&&&:::::&    \n"
            "   &::::&   &::::&    \n"
            "   &::::&   &::::&    \n"
            "    &::::&&&::::&     \n"
            "    &::::::::::&      \n"
            "     &:::::::&&       \n"
            "   &::::::::&   &&&&  \n"
            "  &:::::&&::&  &:::&  \n"
            " &:::::&  &::&&:::&&  \n"
            " &:::::&   &:::::&    \n"
            " &:::::&    &::::&    \n"
            " &::::::&&&&::::::&&  \n"
            "  &&::::::::&&&::::&  \n"
            "    &&&&&&&&   &&&&&  \n";
        std::string bracket1 =
            "       ((((((   \n"
            "     ((::::::(  \n"
            "   ((:::::::(   \n"
            "  (:::::::((    \n"
            "  (::::::(      \n"
            "  (:::::(       \n"
            "  (:::::(       \n"
            "  (:::::(       \n"
            "  (:::::(       \n"
            "  (:::::(       \n"
            "  (:::::(       \n"
            "  (::::::(      \n"
            "  (:::::::((    \n"
            "   ((:::::::(   \n"
            "     ((::::::(  \n"
            "       ((((((   \n";
        std::string bracket2 =
            " ))))))       \n"
            ")::::::))     \n"
            " ):::::::))   \n"
            "  )):::::::)  \n"
            "    )::::::)  \n"
            "     ):::::)  \n"
            "     ):::::)  \n"
            "     ):::::)  \n"
            "     ):::::)  \n"
            "     ):::::)  \n"
            "     ):::::)  \n"
            "    )::::::)  \n"
            "  )):::::::)  \n"
            " ):::::::))   \n"
            ")::::::)      \n"
            " ))))))       \n";
        std::string plus =
            "                      \n"
            "                      \n"
            "                      \n"
            "       +++++++        \n"
            "       +:::::+        \n"
            "       +:::::+        \n"
            " +++++++:::::+++++++  \n"
            " +:::::::::::::::::+  \n"
            " +:::::::::::::::::+  \n"
            " +++++++:::::+++++++  \n"
            "       +:::::+        \n"
            "       +:::::+        \n"
            "       +++++++        \n"
            "                      \n"
            "                      \n"
            "                      \n";
        std::string forwardslash =
            "               ///////  \n"
            "              /:::::/   \n"
            "             /:::::/    \n"
            "            /:::::/     \n"
            "           /:::::/      \n"
            "          /:::::/       \n"
            "         /:::::/        \n"
            "        /:::::/         \n"
            "       /:::::/          \n"
            "      /:::::/           \n"
            "     /:::::/            \n"
            "    /:::::/             \n"
            "   /:::::/              \n"
            "  /:::::/               \n"
            " /:::::/                \n"
            "///////                 \n";
        std::string colon =
            "         \n"
            "         \n"
            " ::::::  \n"
            " ::::::  \n"
            " ::::::  \n"
            "         \n"
            "         \n"
            "         \n"
            " ::::::  \n"
            " ::::::  \n"
            " ::::::  \n"
            "         \n"
            "         \n";
        std::string semicolon =
            "          \n"
            "          \n"
            "  ;;;;;;  \n"
            "  ;::::;  \n"
            "  ;;;;;;  \n"
            "          \n"
            "          \n"
            "          \n"
            "  ;;;;;;  \n"
            "  ;::::;  \n"
            "  ;:::;;  \n"
            " ;:::;    \n"
            " ;;;;     \n"
            "          \n"
            "          \n";
        std::string smaller =
            "      <<<<<<<  \n"
            "     <:::::<   \n"
            "    <:::::<    \n"
            "   <:::::<     \n"
            "  <:::::<      \n"
            " <:::::<       \n"
            "<:::::<        \n"
            " <:::::<       \n"
            "  <:::::<      \n"
            "   <:::::<     \n"
            "    <:::::<    \n"
            "     <:::::<   \n"
            "      <<<<<<<  \n";
        std::string equals =
            "                  \n"
            "                  \n"
            "                  \n"
            "                  \n"
            " ===============  \n"
            " =:::::::::::::=  \n"
            " ===============  \n"
            "                  \n"
            " ===============  \n"
            " =:::::::::::::=  \n"
            " ===============  \n"
            "                  \n"
            "                  \n"
            "                  \n"
            "                  \n";

        std::string greater =
            ">>>>>>>        \n"
            " >:::::>       \n"
            "  >:::::>      \n"
            "   >:::::>     \n"
            "    >:::::>    \n"
            "     >:::::>   \n"
            "      >:::::>  \n"
            "     >:::::>   \n"
            "    >:::::>    \n"
            "   >:::::>     \n"
            "  >:::::>      \n"
            " >:::::>       \n"
            ">>>>>>>        \n";
        std::string questionmark =
            "      ???????       \n"
            "    ??:::::::??     \n"
            "  ??:::::::::::?    \n"
            " ?:::::????:::::?   \n"
            " ?::::?    ?::::?   \n"
            " ?::::?     ?::::?  \n"
            " ??????     ?::::?  \n"
            "           ?::::?   \n"
            "          ?::::?    \n"
            "         ?::::?     \n"
            "        ?::::?      \n"
            "       ?::::?       \n"
            "       ?::::?       \n"
            "       ??::??       \n"
            "        ????        \n"
            "                    \n"
            "        ???         \n"
            "       ??:??        \n"
            "        ???         \n";
        std::string A =
            "               AAA                 \n"
            "              A:::A                \n"
            "             A:::::A               \n"
            "            A:::::::A              \n"
            "           A:::::::::A             \n"
            "          A:::::A:::::A            \n"
            "         A:::::A A:::::A           \n"
            "        A:::::A   A:::::A          \n"
            "       A:::::A     A:::::A         \n"
            "      A:::::AAAAAAAAA:::::A        \n"
            "     A:::::::::::::::::::::A       \n"
            "    A:::::AAAAAAAAAAAAA:::::A      \n"
            "   A:::::A             A:::::A     \n"
            "  A:::::A               A:::::A    \n"
            " A:::::A                 A:::::A   \n"
            "AAAAAAA                   AAAAAAA  \n";
        std::string B =
            "BBBBBBBBBBBBBBBBB     \n"
            "B::::::::::::::::B    \n"
            "B::::::BBBBBB:::::B   \n"
            "BB:::::B     B:::::B  \n"
            "  B::::B     B:::::B  \n"
            "  B::::B     B:::::B  \n"
            "  B::::BBBBBB:::::B   \n"
            "  B:::::::::::::BB    \n"
            "  B::::BBBBBB:::::B   \n"
            "  B::::B     B:::::B  \n"
            "  B::::B     B:::::B  \n"
            "  B::::B     B:::::B  \n"
            "BB:::::BBBBBB::::::B  \n"
            "B:::::::::::::::::B   \n"
            "B::::::::::::::::B    \n"
            "BBBBBBBBBBBBBBBBB     \n";
        std::string C =
            "        CCCCCCCCCCCCC  \n"
            "     CCC::::::::::::C  \n"
            "   CC:::::::::::::::C  \n"
            "  C:::::CCCCCCCC::::C  \n"
            " C:::::C       CCCCCC  \n"
            "C:::::C                \n"
            "C:::::C                \n"
            "C:::::C                \n"
            "C:::::C                \n"
            "C:::::C                \n"
            "C:::::C                \n"
            " C:::::C       CCCCCC  \n"
            "  C:::::CCCCCCCC::::C  \n"
            "   CC:::::::::::::::C  \n"
            "     CCC::::::::::::C  \n"
            "        CCCCCCCCCCCCC  \n";
        std::string D =
            "DDDDDDDDDDDDD          \n"
            "D::::::::::::DDD       \n"
            "D:::::::::::::::DD     \n"
            "DDD:::::DDDDD:::::D    \n"
            "  D:::::D    D:::::D   \n"
            "  D:::::D     D:::::D  \n"
            "  D:::::D     D:::::D  \n"
            "  D:::::D     D:::::D  \n"
            "  D:::::D     D:::::D  \n"
            "  D:::::D     D:::::D  \n"
            "  D:::::D     D:::::D  \n"
            "  D:::::D    D:::::D   \n"
            "DDD:::::DDDDD:::::D    \n"
            "D:::::::::::::::DD     \n"
            "D::::::::::::DDD       \n"
            "DDDDDDDDDDDDD          \n";
        std::string E =
            "EEEEEEEEEEEEEEEEEEEEEE  \n"
            "E::::::::::::::::::::E  \n"
            "E::::::::::::::::::::E  \n"
            "EE::::::EEEEEEEEE::::E  \n"
            "  E:::::E       EEEEEE  \n"
            "  E:::::E               \n"
            "  E::::::EEEEEEEEEE     \n"
            "  E:::::::::::::::E     \n"
            "  E:::::::::::::::E     \n"
            "  E::::::EEEEEEEEEE     \n"
            "  E:::::E               \n"
            "  E:::::E       EEEEEE  \n"
            "EE::::::EEEEEEEE:::::E  \n"
            "E::::::::::::::::::::E  \n"
            "E::::::::::::::::::::E  \n"
            "EEEEEEEEEEEEEEEEEEEEEE  \n";
        std::string F =
            "FFFFFFFFFFFFFFFFFFFFFF  \n"
            "F::::::::::::::::::::F  \n"
            "F::::::::::::::::::::F  \n"
            "FF::::::FFFFFFFFF::::F  \n"
            "  F:::::F       FFFFFF  \n"
            "  F:::::F               \n"
            "  F::::::FFFFFFFFFF     \n"
            "  F:::::::::::::::F     \n"
            "  F:::::::::::::::F     \n"
            "  F::::::FFFFFFFFFF     \n"
            "  F:::::F               \n"
            "  F:::::F               \n"
            "FF:::::::FF             \n"
            "F::::::::FF             \n"
            "F::::::::FF             \n"
            "FFFFFFFFFFF             \n";
        std::string G =
            "        GGGGGGGGGGGGG  \n"
            "     GGG::::::::::::G  \n"
            "   GG:::::::::::::::G  \n"
            "  G:::::GGGGGGGG::::G  \n"
            " G:::::G       GGGGGG  \n"
            "G:::::G                \n"
            "G:::::G                \n"
            "G:::::G    GGGGGGGGGG  \n"
            "G:::::G    G::::::::G  \n"
            "G:::::G    GGGGG::::G  \n"
            "G:::::G        G::::G  \n"
            " G:::::G       G::::G  \n"
            "  G:::::GGGGGGGG::::G  \n"
            "   GG:::::::::::::::G  \n"
            "     GGG::::::GGG:::G  \n"
            "        GGGGGG   GGGG  \n";
        std::string H =
            "HHHHHHHHH     HHHHHHHHH  \n"
            "H:::::::H     H:::::::H  \n"
            "H:::::::H     H:::::::H  \n"
            "HH::::::H     H::::::HH  \n"
            "  H:::::H     H:::::H    \n"
            "  H:::::H     H:::::H    \n"
            "  H::::::HHHHH::::::H    \n"
            "  H:::::::::::::::::H    \n"
            "  H:::::::::::::::::H    \n"
            "  H::::::HHHHH::::::H    \n"
            "  H:::::H     H:::::H    \n"
            "  H:::::H     H:::::H    \n"
            "HH::::::H     H::::::HH  \n"
            "H:::::::H     H:::::::H  \n"
            "H:::::::H     H:::::::H  \n"
            "HHHHHHHHH     HHHHHHHHH  \n";
        std::string I =
            "IIIIIIIIII  \n"
            "I::::::::I  \n"
            "I::::::::I  \n"
            "II::::::II  \n"
            "  I::::I    \n"
            "  I::::I    \n"
            "  I::::I    \n"
            "  I::::I    \n"
            "  I::::I    \n"
            "  I::::I    \n"
            "  I::::I    \n"
            "  I::::I    \n"
            "II::::::II  \n"
            "I::::::::I  \n"
            "I::::::::I  \n"
            "IIIIIIIIII  \n";
        std::string J =
            "          JJJJJJJJJJJ  \n"
            "          J:::::::::J  \n"
            "          J:::::::::J  \n"
            "          JJ:::::::JJ  \n"
            "            J:::::J    \n"
            "            J:::::J    \n"
            "            J:::::J    \n"
            "            J:::::j    \n"
            "            J:::::J    \n"
            "JJJJJJJ     J:::::J    \n"
            "J:::::J     J:::::J    \n"
            "J::::::J   J::::::J    \n"
            "J:::::::JJJ:::::::J    \n"
            " JJ:::::::::::::JJ     \n"
            "   JJ:::::::::JJ       \n"
            "     JJJJJJJJJ         \n";
        std::string K =
            "KKKKKKKKK    KKKKKKK  \n"
            "K:::::::K    K:::::K  \n"
            "K:::::::K    K:::::K  \n"
            "K:::::::K   K::::::K  \n"
            "KK::::::K  K:::::KKK  \n"
            "  K:::::K K:::::K     \n"
            "  K::::::K:::::K      \n"
            "  K:::::::::::K       \n"
            "  K:::::::::::K       \n"
            "  K::::::K:::::K      \n"
            "  K:::::K K:::::K     \n"
            "KK::::::K  K:::::KKK  \n"
            "K:::::::K   K::::::K  \n"
            "K:::::::K    K:::::K  \n"
            "K:::::::K    K:::::K  \n"
            "KKKKKKKKK    KKKKKKK  \n";
        std::string L =
            "LLLLLLLLLLL               \n"
            "L:::::::::L               \n"
            "L:::::::::L               \n"
            "LL:::::::LL               \n"
            "  L:::::L                 \n"
            "  L:::::L                 \n"
            "  L:::::L                 \n"
            "  L:::::L                 \n"
            "  L:::::L                 \n"
            "  L:::::L                 \n"
            "  L:::::L                 \n"
            "  L:::::L         LLLLLL  \n"
            "LL:::::::LLLLLLLLL:::::L  \n"
            "L::::::::::::::::::::::L  \n"
            "L::::::::::::::::::::::L  \n"
            "LLLLLLLLLLLLLLLLLLLLLLLL  \n";
        std::string M =
            "MMMMMMMM               MMMMMMMM  \n"
            "M:::::::M             M:::::::M  \n"
            "M::::::::M           M::::::::M  \n"
            "M:::::::::M         M:::::::::M  \n"
            "M::::::::::M       M::::::::::M  \n"
            "M:::::::::::M     M:::::::::::M  \n"
            "M:::::::M::::M   M::::M:::::::M  \n"
            "M::::::M M::::M M::::M M::::::M  \n"
            "M::::::M  M::::M::::M  M::::::M  \n"
            "M::::::M   M:::::::M   M::::::M  \n"
            "M::::::M    M:::::M    M::::::M  \n"
            "M::::::M     MMMMM     M::::::M  \n"
            "M::::::M               M::::::M  \n"
            "M::::::M               M::::::M  \n"
            "M::::::M               M::::::M  \n"
            "MMMMMMMM               MMMMMMMM  \n";
        std::string N =
            "NNNNNNNN        NNNNNNNN  \n"
            "N:::::::N       N::::::N  \n"
            "N::::::::N      N::::::N  \n"
            "N:::::::::N     N::::::N  \n"
            "N::::::::::N    N::::::N  \n"
            "N:::::::::::N   N::::::N  \n"
            "N:::::::N::::N  N::::::N  \n"
            "N::::::N N::::N N::::::N  \n"
            "N::::::N  N::::N:::::::N  \n"
            "N::::::N   N:::::::::::N  \n"
            "N::::::N    N::::::::::N  \n"
            "N::::::N     N:::::::::N  \n"
            "N::::::N      N::::::::N  \n"
            "N::::::N       N:::::::N  \n"
            "N::::::N        N::::::N  \n"
            "NNNNNNNN         NNNNNNN  \n";
        std::string O =
            "     OOOOOOOOO      \n"
            "   OO:::::::::OO    \n"
            " OO:::::::::::::OO  \n"
            "O:::::::OOO:::::::O \n"
            "O::::::O   O::::::O \n"
            "O:::::O     O:::::O \n"
            "O:::::O     O:::::O \n"
            "O:::::O     O:::::O \n"
            "O:::::O     O:::::O \n"
            "O:::::O     O:::::O \n"
            "O:::::O     O:::::O \n"
            "O::::::O   O::::::O \n"
            "O:::::::OOO:::::::O \n"
            " OO:::::::::::::OO  \n"
            "   OO:::::::::OO    \n"
            "     OOOOOOOOO      \n";
        std::string P =
            "PPPPPPPPPPPPPPPPP     \n"
            "P::::::::::::::::P    \n"
            "P::::::PPPPPP:::::P   \n"
            "PP:::::P     P:::::P  \n"
            "  P::::P     P:::::P  \n"
            "  P::::P     P:::::P  \n"
            "  P::::PPPPPP:::::P   \n"
            "  P:::::::::::::PP    \n"
            "  P::::PPPPPPPPP      \n"
            "  P::::P              \n"
            "  P::::P              \n"
            "  P::::P              \n"
            "PP::::::PP            \n"
            "P::::::::P            \n"
            "P::::::::P            \n"
            "PPPPPPPPPP            \n";
        std::string Q =
            "     QQQQQQQQQ        \n"
            "   QQ:::::::::QQ      \n"
            " QQ:::::::::::::QQ    \n"
            "Q:::::::QQQ:::::::Q   \n"
            "Q::::::O   Q::::::Q   \n"
            "Q:::::O     Q:::::Q   \n"
            "Q:::::O     Q:::::Q   \n"
            "Q:::::O     Q:::::Q   \n"
            "Q:::::O     Q:::::Q   \n"
            "Q:::::O     Q:::::Q   \n"
            "Q:::::O  QQQQ:::::Q   \n"
            "Q::::::O Q::::::::Q   \n"
            "Q:::::::QQ::::::::Q   \n"
            " QQ::::::::::::::Q    \n"
            "   QQ:::::::::::Q     \n"
            "     QQQQQQQQ::::QQ   \n"
            "             Q:::::Q  \n"
            "              QQQQQQ  \n";
        std::string R =
            "RRRRRRRRRRRRRRRRR     \n"
            "R::::::::::::::::R    \n"
            "R::::::RRRRRR:::::R   \n"
            "RR:::::R     R:::::R  \n"
            "  R::::R     R:::::R  \n"
            "  R::::R     R:::::R  \n"
            "  R::::RRRRRR:::::R   \n"
            "  R:::::::::::::RR    \n"
            "  R::::RRRRRR:::::R   \n"
            "  R::::R     R:::::R  \n"
            "  R::::R     R:::::R  \n"
            "  R::::R     R:::::R  \n"
            "RR:::::R     R:::::R  \n"
            "R::::::R     R:::::R  \n"
            "R::::::R     R:::::R  \n"
            "RRRRRRRR     RRRRRRR  \n";
        std::string S =
            "   SSSSSSSSSSSSSSS   \n"
            " SS:::::::::::::::S  \n"
            "S:::::SSSSSS::::::S  \n"
            "S:::::S     SSSSSSS  \n"
            "S:::::S              \n"
            "S:::::S              \n"
            " S::::SSSS           \n"
            "  SS::::::SSSSS      \n"
            "    SSS::::::::SS    \n"
            "       SSSSSS::::S   \n"
            "            S:::::S  \n"
            "            S:::::S  \n"
            "SSSSSSS     S:::::S  \n"
            "S::::::SSSSSS:::::S  \n"
            "S:::::::::::::::SS   \n"
            " SSSSSSSSSSSSSSS     \n";
        std::string T =
            "TTTTTTTTTTTTTTTTTTTTTTT  \n"
            "T:::::::::::::::::::::T  \n"
            "T:::::::::::::::::::::T  \n"
            "T:::::TT:::::::TT:::::T  \n"
            "TTTTTT  T:::::T  TTTTTT  \n"
            "        T:::::T          \n"
            "        T:::::T          \n"
            "        T:::::T          \n"
            "        T:::::T          \n"
            "        T:::::T          \n"
            "        T:::::T          \n"
            "        T:::::T          \n"
            "      TT:::::::TT        \n"
            "      T:::::::::T        \n"
            "      T:::::::::T        \n"
            "      TTTTTTTTTTT        \n";
        std::string U =
            "UUUUUUUU     UUUUUUUU  \n"
            "U::::::U     U::::::U  \n"
            "U::::::U     U::::::U  \n"
            "UU:::::U     U:::::UU  \n"
            " U:::::U     U:::::U   \n"
            " U:::::D     D:::::U   \n"
            " U:::::D     D:::::U   \n"
            " U:::::D     D:::::U   \n"
            " U:::::D     D:::::U   \n"
            " U:::::D     D:::::U   \n"
            " U:::::D     D:::::U   \n"
            " U::::::U   U::::::U   \n"
            " U:::::::UUU:::::::U   \n"
            "  UU:::::::::::::UU    \n"
            "    UU:::::::::UU      \n"
            "      UUUUUUUUU        \n";
        std::string V =
            "VVVVVVVV           VVVVVVVV  \n"
            "V::::::V           V::::::V  \n"
            "V::::::V           V::::::V  \n"
            "V::::::V           V::::::V  \n"
            " V:::::V           V:::::V   \n"
            "  V:::::V         V:::::V    \n"
            "   V:::::V       V:::::V     \n"
            "    V:::::V     V:::::V      \n"
            "     V:::::V   V:::::V       \n"
            "      V:::::V V:::::V        \n"
            "       V:::::V:::::V         \n"
            "        V:::::::::V          \n"
            "         V:::::::V           \n"
            "          V:::::V            \n"
            "           V:::V             \n"
            "            VVV              \n";
        std::string W =
            "WWWWWWWW                           WWWWWWWW  \n"
            "W::::::W                           W::::::W  \n"
            "W::::::W                           W::::::W  \n"
            "W::::::W                           W::::::W  \n"
            " W:::::W           WWWWW           W:::::W   \n"
            "  W:::::W         W:::::W         W:::::W    \n"
            "   W:::::W       W:::::::W       W:::::W     \n"
            "    W:::::W     W:::::::::W     W:::::W      \n"
            "     W:::::W   W:::::W:::::W   W:::::W       \n"
            "      W:::::W W:::::W W:::::W W:::::W        \n"
            "       W:::::W:::::W   W:::::W:::::W         \n"
            "        W:::::::::W     W:::::::::W          \n"
            "         W:::::::W       W:::::::W           \n"
            "          W:::::W         W:::::W            \n"
            "           W:::W           W:::W             \n"
            "            WWW             WWW              \n";
        std::string X =
            "XXXXXXX       XXXXXXX  \n"
            "X:::::X       X:::::X  \n"
            "X:::::X       X:::::X  \n"
            "X::::::X     X::::::X  \n"
            "XXX:::::X   X:::::XXX  \n"
            "   X:::::X X:::::X     \n"
            "    X:::::X:::::X      \n"
            "     X:::::::::X       \n"
            "     X:::::::::X       \n"
            "    X:::::X:::::X      \n"
            "   X:::::X X:::::X     \n"
            "XXX:::::X   X:::::XXX  \n"
            "X::::::X     X::::::X  \n"
            "X:::::X       X:::::X  \n"
            "X:::::X       X:::::X  \n"
            "XXXXXXX       XXXXXXX  \n";
        std::string Y =
            "YYYYYYY       YYYYYYY  \n"
            "Y:::::Y       Y:::::Y  \n"
            "Y:::::Y       Y:::::Y  \n"
            "Y::::::Y     Y::::::Y  \n"
            "YYY:::::Y   Y:::::YYY  \n"
            "   Y:::::Y Y:::::Y     \n"
            "    Y:::::Y:::::Y      \n"
            "     Y:::::::::Y       \n"
            "      Y:::::::Y        \n"
            "       Y:::::Y         \n"
            "       Y:::::Y         \n"
            "       Y:::::Y         \n"
            "       Y:::::Y         \n"
            "    YYYY:::::YYYY      \n"
            "    Y:::::::::::Y      \n"
            "    YYYYYYYYYYYYY      \n";
        std::string Z =
            "ZZZZZZZZZZZZZZZZZZZ  \n"
            "Z:::::::::::::::::Z  \n"
            "Z:::::::::::::::::Z  \n"
            "Z:::ZZZZZZZZ:::::Z   \n"
            "ZZZZZ     Z:::::Z    \n"
            "        Z:::::Z      \n"
            "       Z:::::Z       \n"
            "      Z:::::Z        \n"
            "     Z:::::Z         \n"
            "    Z:::::Z          \n"
            "   Z:::::Z           \n"
            "ZZZ:::::Z     ZZZZZ  \n"
            "Z::::::ZZZZZZZZ:::Z  \n"
            "Z:::::::::::::::::Z  \n"
            "Z:::::::::::::::::Z  \n"
            "ZZZZZZZZZZZZZZZZZZZ  \n";
        std::string sqauareBracket1 =
            "[[[[[[[[[  \n"
            "[:::::::[  \n"
            "[:::::::[  \n"
            "[:::::[[[  \n"
            "[::::[     \n"
            "[::::[     \n"
            "[::::[     \n"
            "[::::[     \n"
            "[::::[     \n"
            "[::::[     \n"
            "[::::[     \n"
            "[::::[     \n"
            "[:::::[[[  \n"
            "[:::::::[  \n"
            "[:::::::[  \n"
            "[[[[[[[[[  \n";
        std::string backslash =
            "\\\\\\\\\\\\\\                 \n"
            " \\:::::\\                \n"
            "  \\:::::\\               \n"
            "   \\:::::\\              \n"
            "    \\:::::\\             \n"
            "     \\:::::\\            \n"
            "      \\:::::\\           \n"
            "       \\:::::\\          \n"
            "        \\:::::\\         \n"
            "         \\:::::\\        \n"
            "          \\:::::\\       \n"
            "           \\:::::\\      \n"
            "            \\:::::\\     \n"
            "             \\:::::\\    \n"
            "              \\:::::\\   \n"
            "               \\\\\\\\\\\\\\  \n";
        std::string squareBracket2 =
            "]]]]]]]]]  \n"
            "]:::::::]  \n"
            "]:::::::]  \n"
            "]]]:::::]  \n"
            "   ]::::]  \n"
            "   ]::::]  \n"
            "   ]::::]  \n"
            "   ]::::]  \n"
            "   ]::::]  \n"
            "   ]::::]  \n"
            "   ]::::]  \n"
            "   ]::::]  \n"
            "]]]:::::]  \n"
            "]:::::::]  \n"
            "]:::::::]  \n"
            "]]]]]]]]]  \n";
        std::string caret =
            "                   \n"
            "                   \n"
            "                   \n"
            "       ^^^         \n"
            "      ^:::^        \n"
            "     ^:::::^       \n"
            "    ^:::::::^      \n"
            "   ^:::::::::^     \n"
            "  ^:::::^:::::^    \n"
            " ^:::::^ ^:::::^   \n"
            "^^^^^^^   ^^^^^^^  \n"
            "                   \n"
            "                   \n"
            "                   \n";
        std::string a =
            "  aaaaaaaaaaaaa     \n"
            "  a::::::::::::a    \n"
            "  aaaaaaaaa:::::a   \n"
            "           a::::a   \n"
            "    aaaaaaa:::::a   \n"
            "  aa::::::::::::a   \n"
            " a::::aaaa::::::a   \n"
            "a::::a    a:::::a   \n"
            "a::::a    a:::::a   \n"
            "a:::::aaaa::::::a   \n"
            " a::::::::::aa:::a  \n"
            "  aaaaaaaaaa  aaaa  \n";
        std::string b =
            "bbbbbbbb              \n"
            "b::::::b              \n"
            "b::::::b              \n"
            "b::::::b              \n"
            " b:::::b              \n"
            " b:::::bbbbbbbbb      \n"
            " b::::::::::::::bb    \n"
            " b::::::::::::::::b   \n"
            " b:::::bbbbb:::::::b  \n"
            " b:::::b    b::::::b  \n"
            " b:::::b     b:::::b  \n"
            " b:::::b     b:::::b  \n"
            " b:::::b     b:::::b  \n"
            " b:::::bbbbbb::::::b  \n"
            " b::::::::::::::::b   \n"
            " b:::::::::::::::b    \n"
            " bbbbbbbbbbbbbbbb     \n";
        std::string c =
            "    cccccccccccccccc  \n"
            "  cc:::::::::::::::c  \n"
            " c:::::::::::::::::c  \n"
            "c:::::::cccccc:::::c  \n"
            "c::::::c     ccccccc  \n"
            "c:::::c               \n"
            "c:::::c               \n"
            "c::::::c     ccccccc  \n"
            "c:::::::cccccc:::::c  \n"
            " c:::::::::::::::::c  \n"
            "  cc:::::::::::::::c  \n"
            "    cccccccccccccccc  \n";
        std::string d =
            "            dddddddd  \n"
            "            d::::::d  \n"
            "            d::::::d  \n"
            "            d::::::d  \n"
            "            d:::::d   \n"
            "    ddddddddd:::::d   \n"
            "  dd::::::::::::::d   \n"
            " d::::::::::::::::d   \n"
            "d:::::::ddddd:::::d   \n"
            "d::::::d    d:::::d   \n"
            "d:::::d     d:::::d   \n"
            "d:::::d     d:::::d   \n"
            "d:::::d     d:::::d   \n"
            "d::::::ddddd::::::dd  \n"
            " d:::::::::::::::::d  \n"
            "  d:::::::::ddd::::d  \n"
            "   ddddddddd   ddddd  \n";
        std::string e =
            "    eeeeeeeeeeee      \n"
            "  ee::::::::::::ee    \n"
            " e::::::eeeee:::::ee  \n"
            "e::::::e     e:::::e  \n"
            "e:::::::eeeee::::::e  \n"
            "e:::::::::::::::::e   \n"
            "e::::::eeeeeeeeeee    \n"
            "e:::::::e             \n"
            "e::::::::e            \n"
            " e::::::::eeeeeeee    \n"
            "  ee:::::::::::::e    \n"
            "    eeeeeeeeeeeeee    \n";
        std::string f =
            "    ffffffffffffffff    \n"
            "   f::::::::::::::::f   \n"
            "  f::::::::::::::::::f  \n"
            "  f::::::fffffff:::::f  \n"
            "  f:::::f       ffffff  \n"
            "  f:::::f               \n"
            " f:::::::ffffff         \n"
            " f::::::::::::f         \n"
            " f::::::::::::f         \n"
            " f:::::::ffffff         \n"
            "  f:::::f               \n"
            "  f:::::f               \n"
            " f:::::::f              \n"
            " f:::::::f              \n"
            " f:::::::f              \n"
            " fffffffff              \n";
        std::string g =
            "   ggggggggg   ggggg  \n"
            "  g:::::::::ggg::::g  \n"
            " g:::::::::::::::::g  \n"
            "g::::::ggggg::::::gg  \n"
            "g:::::g     g:::::g   \n"
            "g:::::g     g:::::g   \n"
            "g:::::g     g:::::g   \n"
            "g::::::g    g:::::g   \n"
            "g:::::::ggggg:::::g   \n"
            " g::::::::::::::::g   \n"
            "  gg::::::::::::::g   \n"
            "    gggggggg::::::g   \n"
            "            g:::::g   \n"
            "gggggg      g:::::g   \n"
            "g:::::gg   gg:::::g   \n"
            " g::::::ggg:::::::g   \n"
            "  gg:::::::::::::g    \n"
            "    ggg::::::ggg      \n"
            "       gggggg         \n";
        std::string h =
            "hhhhhhh               \n"
            "h:::::h               \n"
            "h:::::h               \n"
            "h:::::h               \n"
            " h::::h hhhhh         \n"
            " h::::hh:::::hhh      \n"
            " h::::::::::::::hh    \n"
            " h:::::::hhh::::::h   \n"
            " h::::::h   h::::::h  \n"
            " h:::::h     h:::::h  \n"
            " h:::::h     h:::::h  \n"
            " h:::::h     h:::::h  \n"
            " h:::::h     h:::::h  \n"
            " h:::::h     h:::::h  \n"
            " h:::::h     h:::::h  \n"
            " hhhhhhh     hhhhhhh  \n";
        std::string i =
            "  iiii    \n"
            " i::::i   \n"
            "  iiii    \n"
            "          \n"
            "iiiiiii   \n"
            "i:::::i   \n"
            " i::::i   \n"
            " i::::i   \n"
            " i::::i   \n"
            " i::::i   \n"
            " i::::i   \n"
            " i::::i   \n"
            "i::::::i  \n"
            "i::::::i  \n"
            "i::::::i  \n"
            "iiiiiiii  \n";
        std::string j =
            "             jjjj   \n"
            "            j::::j  \n"
            "             jjjj   \n"
            "                    \n"
            "           jjjjjjj  \n"
            "           j:::::j  \n"
            "            j::::j  \n"
            "            j::::j  \n"
            "            j::::j  \n"
            "            j::::j  \n"
            "            j::::j  \n"
            "            j::::j  \n"
            "            j::::j  \n"
            "            j::::j  \n"
            "            j::::j  \n"
            "            j::::j  \n"
            "            j::::j  \n"
            "  jjjj      j::::j  \n"
            " j::::jj   j:::::j  \n"
            " j::::::jjj::::::j  \n"
            "  jj::::::::::::j   \n"
            "    jjj::::::jjj    \n"
            "       jjjjjj       \n";
        std::string k =
            "kkkkkkkk             \n"
            "k::::::k             \n"
            "k::::::k             \n"
            "k::::::k             \n"
            " k:::::k    kkkkkkk  \n"
            " k:::::k   k:::::k   \n"
            " k:::::k  k:::::k    \n"
            " k:::::k k:::::k     \n"
            " k::::::k:::::k      \n"
            " k:::::::::::k       \n"
            " k:::::::::::k       \n"
            " k::::::k:::::k      \n"
            "k::::::k k:::::k     \n"
            "k::::::k  k:::::k    \n"
            "k::::::k   k:::::k   \n"
            "kkkkkkkk    kkkkkkk  \n";
        std::string l =
            "lllllll   \n"
            "l:::::l   \n"
            "l:::::l   \n"
            "l:::::l   \n"
            " l::::l   \n"
            " l::::l   \n"
            " l::::l   \n"
            " l::::l   \n"
            " l::::l   \n"
            " l::::l   \n"
            " l::::l   \n"
            " l::::l   \n"
            "l::::::l  \n"
            "l::::::l  \n"
            "l::::::l  \n"
            "llllllll  \n";
        std::string m =
            "   mmmmmmm    mmmmmmm     \n"
            " mm:::::::m  m:::::::mm   \n"
            "m::::::::::mm::::::::::m  \n"
            "m::::::::::::::::::::::m  \n"
            "m:::::mmm::::::mmm:::::m  \n"
            "m::::m   m::::m   m::::m  \n"
            "m::::m   m::::m   m::::m  \n"
            "m::::m   m::::m   m::::m  \n"
            "m::::m   m::::m   m::::m  \n"
            "m::::m   m::::m   m::::m  \n"
            "m::::m   m::::m   m::::m  \n"
            "mmmmmm   mmmmmm   mmmmmm  \n";
        std::string n =
            "nnnn  nnnnnnnn      \n"
            "n:::nn::::::::nn    \n"
            "n::::::::::::::nn   \n"
            "nn:::::::::::::::n  \n"
            "  n:::::nnnn:::::n  \n"
            "  n::::n    n::::n  \n"
            "  n::::n    n::::n  \n"
            "  n::::n    n::::n  \n"
            "  n::::n    n::::n  \n"
            "  n::::n    n::::n  \n"
            "  n::::n    n::::n  \n"
            "  nnnnnn    nnnnnn  \n";
        std::string o =
            "   ooooooooooo     \n"
            " oo:::::::::::oo   \n"
            "o:::::::::::::::o  \n"
            "o:::::ooooo:::::o  \n"
            "o::::o     o::::o  \n"
            "o::::o     o::::o  \n"
            "o::::o     o::::o  \n"
            "o::::o     o::::o  \n"
            "o:::::ooooo:::::o  \n"
            "o:::::::::::::::o  \n"
            " oo:::::::::::oo   \n"
            "   ooooooooooo     \n";
        std::string p =
            "ppppp   ppppppppp     \n"
            "p::::ppp:::::::::p    \n"
            "p:::::::::::::::::p   \n"
            "pp::::::ppppp::::::p  \n"
            " p:::::p     p:::::p  \n"
            " p:::::p     p:::::p  \n"
            " p:::::p     p:::::p  \n"
            " p:::::p    p::::::p  \n"
            " p:::::ppppp:::::::p  \n"
            " p::::::::::::::::p   \n"
            " p::::::::::::::pp    \n"
            " p::::::pppppppp      \n"
            " p:::::p              \n"
            " p:::::p              \n"
            "p:::::::p             \n"
            "p:::::::p             \n"
            "p:::::::p             \n"
            "ppppppppp             \n";
        std::string q =
            "   qqqqqqqqq   qqqqq  \n"
            "  q:::::::::qqq::::q  \n"
            " q:::::::::::::::::q  \n"
            "q::::::qqqqq::::::qq  \n"
            "q:::::q     q:::::q   \n"
            "q:::::q     q:::::q   \n"
            "q:::::q     q:::::q   \n"
            "q::::::q    q:::::q   \n"
            "q:::::::qqqqq:::::q   \n"
            " q::::::::::::::::q   \n"
            "  qq::::::::::::::q   \n"
            "    qqqqqqqq::::::q   \n"
            "            q:::::q   \n"
            "            q:::::q   \n"
            "           q:::::::q  \n"
            "           q:::::::q  \n"
            "           q:::::::q  \n"
            "           qqqqqqqqq  \n";
        std::string r =
            "rrrrr   rrrrrrrrr     \n"
            "r::::rrr:::::::::r    \n"
            "r:::::::::::::::::r   \n"
            "rr::::::rrrrr::::::r  \n"
            " r:::::r     r:::::r  \n"
            " r:::::r     rrrrrrr  \n"
            " r:::::r              \n"
            " r:::::r              \n"
            " r:::::r              \n"
            " r:::::r              \n"
            " r:::::r              \n"
            " rrrrrrr              \n";
        std::string s =
            "    ssssssssss     \n"
            "  ss::::::::::s    \n"
            "ss:::::::::::::s   \n"
            "s::::::ssss:::::s  \n"
            " s:::::s  ssssss   \n"
            "   s::::::s        \n"
            "      s::::::s     \n"
            "ssssss   s:::::s   \n"
            "s:::::ssss::::::s  \n"
            "s::::::::::::::s   \n"
            " s:::::::::::ss    \n"
            "  sssssssssss      \n";
        std::string t =
            "         tttt            \n"
            "      ttt:::t            \n"
            "      t:::::t            \n"
            "      t:::::t            \n"
            "ttttttt:::::ttttttt      \n"
            "t:::::::::::::::::t      \n"
            "t:::::::::::::::::t      \n"
            "tttttt:::::::tttttt      \n"
            "      t:::::t            \n"
            "      t:::::t            \n"
            "      t:::::t            \n"
            "      t:::::t    tttttt  \n"
            "      t::::::tttt:::::t  \n"
            "      tt::::::::::::::t  \n"
            "        tt:::::::::::tt  \n"
            "          ttttttttttt    \n";
        std::string u =
            "uuuuuu    uuuuuu    \n"
            "u::::u    u::::u    \n"
            "u::::u    u::::u    \n"
            "u::::u    u::::u    \n"
            "u::::u    u::::u    \n"
            "u::::u    u::::u    \n"
            "u::::u    u::::u    \n"
            "u:::::uuuu:::::u    \n"
            "u:::::::::::::::uu  \n"
            " u:::::::::::::::u  \n"
            "  uu::::::::uu:::u  \n"
            "    uuuuuuuu  uuuu  \n";
        std::string v =
            "vvvvvvv           vvvvvvv  \n"
            " v:::::v         v:::::v   \n"
            "  v:::::v       v:::::v    \n"
            "   v:::::v     v:::::v     \n"
            "    v:::::v   v:::::v      \n"
            "     v:::::v v:::::v       \n"
            "      v:::::v:::::v        \n"
            "       v:::::::::v         \n"
            "        v:::::::v          \n"
            "         v:::::v           \n"
            "          v:::v            \n"
            "           vvv             \n";
        std::string w =
            "wwwwwww           wwwww           wwwwwww  \n"
            " w:::::w         w:::::w         w:::::w   \n"
            "  w:::::w       w:::::::w       w:::::w    \n"
            "   w:::::w     w:::::::::w     w:::::w     \n"
            "    w:::::w   w:::::w:::::w   w:::::w      \n"
            "     w:::::w w:::::w w:::::w w:::::w       \n"
            "      w:::::w:::::w   w:::::w:::::w        \n"
            "       w:::::::::w     w:::::::::w         \n"
            "        w:::::::w       w:::::::w          \n"
            "         w:::::w         w:::::w           \n"
            "          w:::w           w:::w            \n"
            "           www             www             \n";
        std::string x =
            "xxxxxxx      xxxxxxx  \n"
            " x:::::x    x:::::x   \n"
            "  x:::::x  x:::::x    \n"
            "   x:::::xx:::::x     \n"
            "    x::::::::::x      \n"
            "     x::::::::x       \n"
            "     x::::::::x       \n"
            "    x::::::::::x      \n"
            "   x:::::xx:::::x     \n"
            "  x:::::x  x:::::x    \n"
            " x:::::x    x:::::x   \n"
            "xxxxxxx      xxxxxxx  \n";
        std::string y =
            "yyyyyyy           yyyyyyy  \n"
            " y:::::y         y:::::y   \n"
            "  y:::::y       y:::::y    \n"
            "   y:::::y     y:::::y     \n"
            "    y:::::y   y:::::y      \n"
            "     y:::::y y:::::y       \n"
            "      y:::::y:::::y        \n"
            "       y:::::::::y         \n"
            "        y:::::::y          \n"
            "         y:::::y           \n"
            "        y:::::y            \n"
            "       y:::::y             \n"
            "      y:::::y              \n"
            "     y:::::y               \n"
            "    y:::::y                \n"
            "   y:::::y                 \n"
            "  yyyyyyy                  \n";
        std::string z =
            "zzzzzzzzzzzzzzzzz  \n"
            "z:::::::::::::::z  \n"
            "z::::::::::::::z   \n"
            "zzzzzzzz::::::z    \n"
            "      z::::::z     \n"
            "     z::::::z      \n"
            "    z::::::z       \n"
            "   z::::::z        \n"
            "  z::::::zzzzzzzz  \n"
            " z::::::::::::::z  \n"
            "z:::::::::::::::z  \n"
            "zzzzzzzzzzzzzzzzz  \n";
        std::string space =
            "    \n"
            "    \n"
            "    \n"
            "    \n"
            "    \n"
            "    \n"
            "    \n"
            "    \n"
            "    \n"
            "    \n"
            "    \n"
            "    \n";
        std::string tilde =
            "                         \n"
            "                         \n"
            "                         \n"
            "                         \n"
            "                         \n"
            "    ~~~~~~~~~    ~~~~~~  \n"
            "  ~~:::::::::~  ~:::::~  \n"
            " ~:::::~~:::::~~:::::~   \n"
            "~:::::~  ~::::::::::~    \n"
            "~~~~~~    ~~~~~~~~~~     \n"
            "                         \n"
            "                         \n"
            "                         \n"
            "                         \n"
            "                         \n";
    };

} // namespace AsciiArt